version: '3.8'

services:
  # Database
  database:
    image: postgres:15
    container_name: habit-db
    environment:
      POSTGRES_DB: habittracker
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # Backend
  backend:
    build: ./backend
    container_name: habit-backend
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: "postgresql://admin:password123@database:5432/habittracker"
    ports:
      - "3000:3000"
    depends_on:
      - database
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend
  frontend:
    build: ./frontend
    container_name: habit-frontend
    env_file:
      - ./frontend/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  db_data: